#!/bin/bash

# OAuth Configuration Verification Script
# Run after updating Google OAuth Console

echo "======================================="
echo "OAuth Configuration Verification"
echo "======================================="
echo ""

# Expected values
CLIENT_ID="5562559893-1ufv0knok8k4679kr35p7aqdhp55drg0.apps.googleusercontent.com"
SUPABASE_CALLBACK="https://gppebtrshbvuzatmebhr.supabase.co/auth/v1/callback"
FRONTEND_URL="https://aica-5562559893.southamerica-east1.run.app"

echo "✓ Client ID: $CLIENT_ID"
echo "✓ Supabase Callback: $SUPABASE_CALLBACK"
echo "✓ Frontend URL: $FRONTEND_URL"
echo ""

echo "======================================="
echo "MANUAL VERIFICATION REQUIRED"
echo "======================================="
echo ""
echo "Please verify in Google OAuth Console:"
echo "https://console.cloud.google.com/apis/credentials"
echo ""
echo "1. Find Client ID: ${CLIENT_ID:0:20}..."
echo "2. Click Edit"
echo "3. Verify 'Authorized redirect URIs' contains:"
echo ""
echo "   ✅ $SUPABASE_CALLBACK"
echo "   ✅ $FRONTEND_URL"
echo "   ✅ http://localhost:5173"
echo ""
echo "4. If missing, add the Supabase callback URL"
echo "5. Click SAVE"
echo "6. Wait 1-2 minutes for propagation"
echo ""
echo "======================================="
echo "TEST OAUTH FLOW"
echo "======================================="
echo ""
echo "1. Open incognito: $FRONTEND_URL"
echo "2. Open DevTools Console (F12)"
echo "3. Click 'Login com Google'"
echo "4. Check logs for:"
echo "   - [OAuth Debug] Redirect URL: $FRONTEND_URL"
echo "   - [CookieAdapter] code_verifier {valueLength: 112}"
echo "   - Should NOT see: 401 Unauthorized"
echo ""
echo "Expected success:"
echo "   ✅ [useAuth] Auth state changed: SIGNED_IN"
echo ""
