/**
 * Unified Event Types
 * Polymorphic event system for timeline aggregation
 * Supports 7 event sources: WhatsApp, moments, tasks, approvals, activities, questions, summaries
 */

/**
 * Display data for UI rendering (auto-generated by service)
 */
export interface EventDisplayData {
  icon: string
  title: string
  label: string
  color: string
  preview: string
}

/**
 * Base event structure shared by all event types
 */
export interface BaseEvent {
  id: string
  created_at: string
  user_id: string
  displayData: EventDisplayData
}

/**
 * Event source types - all possible sources in the timeline
 */
export type EventSource =
  | 'whatsapp'
  | 'moment'
  | 'task'
  | 'approval'
  | 'activity'
  | 'question'
  | 'summary'

/**
 * Sentiment types for emotional context
 */
export type EventSentiment = 'positive' | 'neutral' | 'negative' | 'mixed'

/**
 * WhatsApp message event
 */
export interface WhatsAppEvent extends BaseEvent {
  source: 'whatsapp'
  content: string
  contact_name?: string
  contact_number?: string
  message_type: 'text' | 'audio' | 'image' | 'document' | 'video'
  direction: 'incoming' | 'outgoing'
  sentiment?: EventSentiment
  tags?: string[]
}

/**
 * Moment/journal entry event
 */
export interface MomentEvent extends BaseEvent {
  source: 'moment'
  content: string
  title?: string
  emotion?: string
  energy_level?: number
  tags?: string[]
  sentiment?: EventSentiment
  has_audio?: boolean
  audio_duration_seconds?: number
}

/**
 * Task event (from Atlas module)
 */
export interface TaskEvent extends BaseEvent {
  source: 'task'
  title: string
  description?: string
  status: 'pending' | 'in_progress' | 'completed' | 'cancelled'
  priority: 'urgent_important' | 'not_urgent_important' | 'urgent_not_important' | 'not_urgent_not_important'
  completed_at?: string
  due_date?: string
  xp_earned?: number
}

/**
 * Approval/decision event
 */
export interface ApprovalEvent extends BaseEvent {
  source: 'approval'
  title: string
  description?: string
  status: 'pending' | 'approved' | 'rejected'
  approved_at?: string
  rejected_at?: string
}

/**
 * Activity event (general system activity)
 */
export interface ActivityEvent extends BaseEvent {
  source: 'activity'
  activity_type: string
  description: string
  metadata?: Record<string, unknown>
  xp_earned?: number
}

/**
 * Daily question event
 */
export interface QuestionEvent extends BaseEvent {
  source: 'question'
  question_text: string
  response?: string
  answered_at?: string
  skipped?: boolean
  xp_earned?: number
}

/**
 * Weekly summary event
 */
export interface SummaryEvent extends BaseEvent {
  source: 'summary'
  week_start: string
  week_end: string
  highlights?: string[]
  mood_average?: number
  moments_count?: number
  tasks_completed?: number
  reflection?: string
}

/**
 * Union type for all possible events
 */
export type UnifiedEvent =
  | WhatsAppEvent
  | MomentEvent
  | TaskEvent
  | ApprovalEvent
  | ActivityEvent
  | QuestionEvent
  | SummaryEvent

/**
 * Type guards for event source checking
 */
export function isWhatsAppEvent(event: UnifiedEvent): event is WhatsAppEvent {
  return event.source === 'whatsapp'
}

export function isMomentEvent(event: UnifiedEvent): event is MomentEvent {
  return event.source === 'moment'
}

export function isTaskEvent(event: UnifiedEvent): event is TaskEvent {
  return event.source === 'task'
}

export function isApprovalEvent(event: UnifiedEvent): event is ApprovalEvent {
  return event.source === 'approval'
}

export function isActivityEvent(event: UnifiedEvent): event is ActivityEvent {
  return event.source === 'activity'
}

export function isQuestionEvent(event: UnifiedEvent): event is QuestionEvent {
  return event.source === 'question'
}

export function isSummaryEvent(event: UnifiedEvent): event is SummaryEvent {
  return event.source === 'summary'
}

/**
 * Timeline filter options
 */
export interface TimelineFilters {
  sources: EventSource[]
  dateRange: 'today' | 'last7' | 'last30' | 'last90' | 'all'
  searchTerm?: string
  sentiments?: EventSentiment[]
  tags?: string[]
}

/**
 * Type aliases for backward compatibility with component imports
 */
export type UnifiedEventSource = EventSource
export type TimelineFilter = TimelineFilters

/**
 * Default filter configuration
 * Note: Only include sources that have corresponding database tables
 * - task, activity, approval: Tables don't exist yet (future Atlas integration)
 * - whatsapp: whatsapp_messages table ✅ (Issue #138)
 * - moment: moments table
 * - question: question_responses table
 * - summary: weekly_summaries table
 */
export const DEFAULT_TIMELINE_FILTERS: TimelineFilters = {
  sources: ['whatsapp', 'moment', 'question', 'summary'],
  dateRange: 'last30',
}

/**
 * Timeline statistics
 */
export interface TimelineStats {
  totalEvents: number
  eventsByType: Record<EventSource, number>
  averageSentiment?: EventSentiment
  topTags?: string[]
}
