/**
 * Weekly Summary Types
 * Tipos para resumo semanal inteligente (Feature 7)
 */

import { Moment } from './moment'

export type WeeklyEmotionalTrend = 'ascending' | 'stable' | 'descending' | 'volatile'

export interface KeyMoment {
  id: string
  preview: string
  sentiment: string
  created_at: string
}

export type WeeklySummarySource = 'ai' | 'fallback'

export interface WeeklySummaryData {
  emotionalTrend: WeeklyEmotionalTrend
  trendJustification?: string
  dominantEmotions: string[]
  keyMoments: KeyMoment[]
  insights: string[]
  suggestedFocus: string
  /** Indicates whether the summary was generated by AI or by the local fallback heuristic */
  source?: WeeklySummarySource
}

export interface WeeklySummary {
  id: string
  user_id: string

  // Time period
  week_number: number
  year: number
  period_start: string // ISO date
  period_end: string // ISO date

  // AI-generated summary
  summary_data: WeeklySummaryData

  // User reflection
  user_reflection?: string

  // Timestamps
  generated_at: string
  viewed_at?: string
}

export interface CreateWeeklySummaryInput {
  week_number: number
  year: number
  period_start: Date
  period_end: Date
  moments: Moment[]
}

export interface WeeklySummaryWithReflection extends WeeklySummary {
  reflection_added: boolean
  cp_earned: number
  quality_score?: number
  quality_feedback?: string
  quality_tier?: 'low' | 'medium' | 'high' | 'exceptional'
}

// Helper: Get current ISO week number (ISO-8601: weeks start Monday)
export function getCurrentWeekNumber(): { week: number; year: number } {
  const now = new Date()
  const target = new Date(now.valueOf())
  // ISO week: adjust to nearest Thursday (ISO weeks are defined by Thursday)
  const dayNr = (now.getDay() + 6) % 7 // Monday=0, Sunday=6
  target.setDate(target.getDate() - dayNr + 3) // Nearest Thursday
  const year = target.getFullYear()
  const jan4 = new Date(year, 0, 4) // Jan 4 is always in week 1
  const diff = target.getTime() - jan4.getTime()
  const week = 1 + Math.round(diff / (7 * 24 * 60 * 60 * 1000))
  return { week, year }
}

// Helper: Get week date range
export function getWeekDateRange(year: number, week: number): { start: Date; end: Date } {
  const simple = new Date(year, 0, 1 + (week - 1) * 7)
  const dow = simple.getDay()
  const ISOweekStart = simple
  if (dow <= 4) ISOweekStart.setDate(simple.getDate() - simple.getDay() + 1)
  else ISOweekStart.setDate(simple.getDate() + 8 - simple.getDay())
  const start = new Date(ISOweekStart)
  const end = new Date(ISOweekStart)
  end.setDate(end.getDate() + 6)
  return { start, end }
}

// Emotional trend labels (Portuguese display names)
export const EMOTIONAL_TREND_LABELS: Record<WeeklyEmotionalTrend, string> = {
  ascending: 'Ascendente',
  stable: 'Estável',
  descending: 'Em declínio',
  volatile: 'Volátil',
}

// Emotional trend descriptions
export const EMOTIONAL_TREND_DESCRIPTIONS: Record<WeeklyEmotionalTrend, string> = {
  ascending: 'Sua energia emocional está crescendo! Continue assim.',
  stable: 'Você está equilibrado e consistente.',
  descending: 'Parece que sua energia está diminuindo. Que tal pausar e refletir?',
  volatile: 'Você viveu altos e baixos esta semana. Vamos explorar o que causou essas oscilações.',
}

// Emotional trend colors
export const EMOTIONAL_TREND_COLORS: Record<WeeklyEmotionalTrend, string> = {
  ascending: '#10b981', // green-500
  stable: '#3b82f6', // blue-500
  descending: '#f97316', // orange-500
  volatile: '#8B5CF6', // violet-500
}
