/**
 * Podcast Workspace Types
 *
 * Defines the complete state and action system for the podcast workspace,
 * which manages the multi-stage workflow for podcast episode creation:
 * 1. Setup - Guest information and episode metadata
 * 2. Research - Dossier generation and custom sources
 * 3. Pauta - Script and topic management
 * 4. Production - Recording session
 *
 * Migration Note: Consolidated from _deprecated/modules/podcast/types/workspace.ts
 *
 * @see StudioState for parent container state
 * @see StudioProject for episode-level metadata
 */

// ============================================
// IMPORTED TYPES
// ============================================

/**
 * Topic structure for episode script.
 * Imported from _deprecated/modules/podcast/types.ts
 */
export interface Topic {
  id: string;
  text: string;
  completed: boolean;
  order: number;
  archived: boolean;
  categoryId?: string;
  sponsorScript?: string;
}

/**
 * Topic category for organizing script sections.
 * Imported from _deprecated/modules/podcast/types.ts
 */
export interface TopicCategory {
  id: string;
  name: string;
  color: string;
  episode_id: string;
  description?: string;
  icon?: string;
  order?: number;
  created_at?: string;
  updated_at?: string;
}

/**
 * Technical sheet with detailed guest information.
 * Used in dossier generation for comprehensive guest research.
 */
export interface TechnicalSheet {
  fullName?: string;
  nicknames?: string[];
  birthInfo?: {
    date?: string;
    city?: string;
    state?: string;
    country?: string;
  };
  familyInfo?: {
    mother?: string;
    father?: string;
    siblings?: string[];
  };
  residenceHistory?: {
    city: string;
    state?: string;
    country: string;
    period?: string;
  }[];
  traveledCountries?: string[];
  education?: {
    degree: string;
    institution: string;
    year?: string;
  }[];
  careerHighlights?: {
    title: string;
    organization: string;
    period?: string;
  }[];
  preferences?: {
    food?: string[];
    hobbies?: string[];
    sports?: string[];
    music?: string[];
  };
  socialMedia?: {
    platform: string;
    handle: string;
  }[];
  keyFacts?: string[];
}

/**
 * Guest dossier generated by AI.
 * Contains comprehensive research about the guest.
 */
export interface Dossier {
  guestName: string;
  episodeTheme: string;
  biography: string;
  technicalSheet?: TechnicalSheet;
  controversies: string[];
  suggestedTopics: string[];
  iceBreakers: string[];
}

/**
 * Saved pauta (script) from database.
 * Represents a complete generated script with all sections.
 */
export interface SavedPauta {
  id: string;
  episode_id: string;
  user_id: string;
  guest_name: string;
  theme: string;
  version: number;
  is_active: boolean;
  research_summary: string | null;
  biography: string | null;
  key_facts: string[] | null;
  controversies: any[] | null;
  technical_sheet: any | null;
  outline_title: string | null;
  estimated_duration: number | null;
  confidence_score: number | null;
  tone: string | null;
  depth: string | null;
  focus_areas: string[] | null;
  ice_breakers: string[] | null;
  additional_context: string | null;
  created_at: string;
  updated_at: string;
}

// ============================================
// CUSTOM SOURCE TYPES
// ============================================

/**
 * Custom research source added by user.
 *
 * CONFLICT RESOLUTION: This type had duplicate definitions:
 * 1. _deprecated/modules/podcast/types/workspace.ts - with 'text' | 'url' | 'file' types
 * 2. _deprecated/modules/podcast/types.ts - with 'file' | 'link' | 'text' types
 * 3. src/modules/studio/services/podcastAIService.ts - with 'article' | 'video' | 'social' | 'other' types
 *
 * RESOLUTION: We use workspace.ts definition as it's the most complete for the workspace context.
 * The service layer version is kept separate for AI service operations.
 *
 * @see podcastAIService.CustomSource for AI service version
 */
export interface WorkspaceCustomSource {
  id: string;
  /** Type of custom source */
  type: 'text' | 'url' | 'file';
  /** Content: raw text, URL string, or file path */
  content: string;
  /** Optional label for display */
  label?: string;
  /** When this source was added */
  createdAt: Date;
}

// ============================================
// STAGE DEFINITIONS
// ============================================

/**
 * Unique identifier for each workflow stage.
 * Stages must be completed in order.
 */
export type PodcastStageId = 'setup' | 'research' | 'pauta' | 'production';

/**
 * Stage metadata for UI display.
 * Used in navigation and progress tracking.
 */
export interface PodcastStage {
  id: PodcastStageId;
  label: string;
  shortLabel: string;
  icon: string;
  description: string;
}

/**
 * Complete stage configuration.
 * Exported as constant for use in components.
 */
export const PODCAST_STAGES: PodcastStage[] = [
  {
    id: 'setup',
    label: '1. Configuração',
    shortLabel: 'Setup',
    icon: 'User',
    description: 'Informações básicas do episódio e convidado',
  },
  {
    id: 'research',
    label: '2. Pesquisa',
    shortLabel: 'Pesquisa',
    icon: 'Sparkles',
    description: 'Dossier e pesquisa sobre o convidado',
  },
  {
    id: 'pauta',
    label: '3. Pauta',
    shortLabel: 'Pauta',
    icon: 'FileText',
    description: 'Roteiro e tópicos do episódio',
  },
  {
    id: 'production',
    label: '4. Gravação',
    shortLabel: 'Gravação',
    icon: 'Mic',
    description: 'Gravar o episódio',
  },
];

// ============================================
// STAGE-SPECIFIC STATE TYPES
// ============================================

/**
 * Stage 1: Setup State
 * Captures guest information and episode metadata.
 */
export interface SetupState {
  /** Type of guest (affects dossier generation) */
  guestType: 'public_figure' | 'common_person' | null;

  /** Guest's full name */
  guestName: string;

  /** Reference for AI search (title, occupation) or manual occupation */
  guestReference: string;

  /**
   * Manual bio notes for common people (UI-only field).
   * NOT persisted to database - used only during setup flow.
   * The actual biography is stored in research.dossier.biography.
   */
  guestBio: string;

  /** Platform contact ID (from platform_contacts table) */
  guestContactId: string | null;

  /** Contact information */
  phone: string;
  email: string;

  /** Episode theme/topic */
  theme: string;

  /** Whether theme was auto-suggested or manually entered */
  themeMode: 'auto' | 'manual';

  /** Podcast season number */
  season: string;

  /** Recording location */
  location: string;

  /** Scheduled recording date (ISO format) */
  scheduledDate: string;

  /** Scheduled recording time */
  scheduledTime: string;

  // AI search state
  /** Whether AI search is in progress */
  isSearching: boolean;

  /** Results from guest profile search */
  searchResults: any | null;
}

/**
 * Stage 2: Research State
 * Manages dossier generation and custom research sources.
 */
export interface ResearchState {
  /** Generated guest dossier from AI */
  dossier: Dossier | null;

  /** User-provided custom research sources */
  customSources: WorkspaceCustomSource[];

  /** Whether dossier is being generated */
  isGenerating: boolean;

  /** Timestamp of last successful generation */
  lastGenerated: Date | null;

  /** Error message if generation failed */
  error: string | null;

  /** Deep research result (from wizard or manual deep research) */
  deepResearch: import('../types/studio').DeepResearchResult | null;
}

/**
 * Stage 3: Pauta (Script) State
 * Manages episode script, topics, and categories.
 */
export interface PautaState {
  /** List of topics for the episode */
  topics: Topic[];

  /** Categories for organizing topics */
  categories: TopicCategory[];

  /** Previously saved pautas for this episode */
  savedPautas: SavedPauta[];

  /** ID of currently active pauta */
  activePautaId: string | null;

  /** Whether pauta is being generated */
  isGenerating: boolean;
}

/**
 * Stage 4: Production State
 * Manages recording session state.
 */
export interface ProductionState {
  /** Whether recording is active */
  isRecording: boolean;

  /** Whether recording is paused */
  isPaused: boolean;

  /** Total recording duration in seconds */
  duration: number;

  /** When recording started */
  startedAt: Date | null;

  /** When recording finished */
  finishedAt: Date | null;

  /** Currently active topic ID */
  currentTopicId: string | null;

  /** Path to recording file */
  recordingFilePath: string | null;
}

// ============================================
// WORKSPACE STATE
// ============================================

/**
 * Complete workspace state for podcast episode creation.
 *
 * IMPORTANT: This is a CHILD state managed within StudioState.
 * - StudioState.mode === 'WORKSPACE' activates this
 * - StudioState.currentProject contains episode metadata
 * - This state manages the multi-stage workflow
 *
 * @see StudioState for parent container
 */
export interface PodcastWorkspaceState {
  // Navigation
  /** Current active stage */
  currentStage: PodcastStageId;

  /** Stages that have been visited (for progress tracking) */
  visitedStages: PodcastStageId[];

  // Stage states
  setup: SetupState;
  research: ResearchState;
  pauta: PautaState;
  production: ProductionState;

  // Global metadata
  /** Episode ID (maps to StudioProject.id) */
  episodeId: string;

  /** Show ID (maps to StudioProject.showId) */
  showId: string;

  /** Show title (denormalized for display) */
  showTitle: string;

  // Save state
  /** Timestamp of last successful save */
  lastSaved: Date | null;

  /** Whether there are unsaved changes */
  isDirty: boolean;

  /** Whether async operation is in progress */
  isLoading: boolean;

  /** Error message if operation failed */
  error: string | null;
}

// ============================================
// ACTIONS
// ============================================

/**
 * All possible actions for workspace state management.
 * Uses discriminated union for type safety.
 */
export type WorkspaceAction =
  // Navigation
  | { type: 'SET_STAGE'; payload: PodcastStageId }
  | { type: 'MARK_STAGE_VISITED'; payload: PodcastStageId }

  // Setup actions
  | { type: 'UPDATE_SETUP'; payload: Partial<SetupState> }
  | { type: 'SET_GUEST_TYPE'; payload: 'public_figure' | 'common_person' }
  | { type: 'SET_GUEST_NAME'; payload: string }
  | { type: 'SET_THEME'; payload: string }
  | { type: 'SET_SEARCH_RESULTS'; payload: any }

  // Research actions
  | { type: 'UPDATE_RESEARCH'; payload: Partial<ResearchState> }
  | { type: 'SET_DOSSIER'; payload: Dossier }
  | { type: 'ADD_CUSTOM_SOURCE'; payload: WorkspaceCustomSource }
  | { type: 'REMOVE_CUSTOM_SOURCE'; payload: string }
  | { type: 'START_DOSSIER_GENERATION' }
  | { type: 'FINISH_DOSSIER_GENERATION'; payload: Dossier }
  | { type: 'SET_RESEARCH_ERROR'; payload: string }

  // Pauta actions
  | { type: 'UPDATE_PAUTA'; payload: Partial<PautaState> }
  | { type: 'SET_TOPICS'; payload: Topic[] }
  | { type: 'ADD_TOPIC'; payload: Topic }
  | { type: 'UPDATE_TOPIC'; payload: { id: string; updates: Partial<Topic> } }
  | { type: 'REMOVE_TOPIC'; payload: string }
  | { type: 'REORDER_TOPICS'; payload: Topic[] }
  | { type: 'SET_CATEGORIES'; payload: TopicCategory[] }
  | { type: 'ADD_CATEGORY'; payload: TopicCategory }
  | { type: 'SET_SAVED_PAUTAS'; payload: SavedPauta[] }
  | { type: 'SET_ACTIVE_PAUTA'; payload: string | null }

  // Production actions
  | { type: 'UPDATE_PRODUCTION'; payload: Partial<ProductionState> }
  | { type: 'START_RECORDING' }
  | { type: 'PAUSE_RECORDING' }
  | { type: 'RESUME_RECORDING' }
  | { type: 'STOP_RECORDING' }
  | { type: 'UPDATE_DURATION'; payload: number }
  | { type: 'SET_CURRENT_TOPIC'; payload: string | null }

  // Global actions
  | { type: 'HYDRATE'; payload: Partial<PodcastWorkspaceState> }
  | { type: 'MARK_SAVED' }
  | { type: 'MARK_DIRTY' }
  | { type: 'SET_LOADING'; payload: boolean }
  | { type: 'SET_ERROR'; payload: string | null }
  | { type: 'RESET_WORKSPACE' };

// ============================================
// ACTIONS INTERFACE
// ============================================

/**
 * Actions available through PodcastWorkspaceContext.
 * These provide type-safe wrappers around dispatch calls.
 */
export interface WorkspaceActions {
  // Navigation
  /** Navigate to a specific stage */
  setStage: (stageId: PodcastStageId) => void;

  // Setup actions
  /** Update setup state (partial updates) */
  updateSetup: (updates: Partial<SetupState>) => void;

  /** Set guest type (affects dossier generation) */
  setGuestType: (type: 'public_figure' | 'common_person') => void;

  /** Search for guest profile using AI */
  searchGuestProfile: (name: string, reference: string) => Promise<void>;

  // Research actions
  /** Generate dossier for the first time */
  generateDossier: () => Promise<void>;

  /** Regenerate existing dossier */
  regenerateDossier: () => Promise<void>;

  /** Run deep research on the guest */
  deepResearch: (depth?: 'quick' | 'standard' | 'deep') => Promise<void>;

  /** Add custom research source */
  addCustomSource: (source: WorkspaceCustomSource) => void;

  /** Remove custom research source */
  removeCustomSource: (sourceId: string) => void;

  // Pauta actions
  /** Add new topic to script */
  addTopic: (topic: Omit<Topic, 'id'>) => Promise<void>;

  /** Update existing topic */
  updateTopic: (topicId: string, updates: Partial<Topic>) => Promise<void>;

  /** Remove topic from script */
  removeTopic: (topicId: string) => Promise<void>;

  /** Reorder topics in script */
  reorderTopics: (topics: Topic[]) => Promise<void>;

  /** Generate complete pauta using AI */
  generatePauta: (config: any) => Promise<void>;

  /** Load saved pautas from database */
  loadSavedPautas: () => Promise<void>;

  // Production actions
  /** Start recording session */
  startRecording: () => void;

  /** Pause recording */
  pauseRecording: () => void;

  /** Resume recording */
  resumeRecording: () => void;

  /** Stop recording session */
  stopRecording: () => void;

  /** Set currently active topic */
  setCurrentTopic: (topicId: string | null) => void;

  /** Update recording duration (incremental timer) */
  updateDuration: (seconds: number) => void;

  /** Set pauta categories (bulk update) */
  setCategories: (categories: TopicCategory[]) => void;

  // Global actions
  /** Save workspace state to database */
  save: () => Promise<void>;

  /** Load workspace state from database */
  hydrate: (data: Partial<PodcastWorkspaceState>) => void;
}

// ============================================
// COMPLETION STATUS
// ============================================

/**
 * Stage completion status for progress tracking.
 */
export type StageCompletionStatus = 'complete' | 'partial' | 'none';

/**
 * Map of completion status for all stages.
 * Used to show progress indicators in UI.
 */
export type StageCompletionMap = {
  [K in PodcastStageId]: StageCompletionStatus;
};

// ============================================
// HELPER TYPES
// ============================================

/**
 * Result of loading workspace from database.
 * Includes state and any errors that occurred.
 */
export interface WorkspaceLoadResult {
  state: PodcastWorkspaceState;
  error: string | null;
}

/**
 * Configuration for auto-save behavior.
 */
export interface AutoSaveConfig {
  /** Enable/disable auto-save */
  enabled: boolean;

  /** Debounce delay in milliseconds */
  debounceMs: number;

  /** Show save status indicator */
  showStatus: boolean;
}
