/**
 * Health Score Types
 * Issue #144: [WhatsApp AI] feat: Automated Relationship Health Score Calculation
 *
 * Types for contact health scores, history tracking, alerts, and at-risk contacts.
 */

// ============================================================================
// HEALTH SCORE CORE TYPES
// ============================================================================

/**
 * Trend direction based on recent health score history
 */
export type HealthScoreTrend = 'improving' | 'stable' | 'declining' | 'new';

/**
 * Risk level based on health score value
 */
export type RiskLevel = 'critical' | 'high' | 'moderate' | 'healthy';

/**
 * Alert types generated by health score calculations
 */
export type HealthAlertType =
  | 'score_critical'      // Score dropped below 20
  | 'score_low'           // Score dropped below 40
  | 'rapid_decline'       // Score dropped 20+ points in 7 days
  | 'no_interaction'      // No messages in 30+ days
  | 'sentiment_negative'; // Sustained negative sentiment

/**
 * Calculation method for health score
 */
export type CalculationMethod = 'automated' | 'manual' | 'migration';

// ============================================================================
// HEALTH SCORE COMPONENTS
// ============================================================================

/**
 * Breakdown of health score by component
 * Total: frequency (0-25) + recency (0-25) + sentiment (0-20)
 *        + reciprocity (0-15) + depth (0-15) = 0-100
 */
export interface HealthScoreComponents {
  /** Message frequency score (0-25) */
  frequency_score: number;
  /** Recency of last message score (0-25) */
  recency_score: number;
  /** Average sentiment score (0-20) */
  sentiment_score: number;
  /** Balance of incoming/outgoing messages (0-15) */
  reciprocity_score: number;
  /** Conversation depth/diversity (0-15) */
  depth_score: number;
  /** Total calculated score (0-100) */
  total_score: number;
  /** Number of messages analyzed */
  messages_analyzed: number;
  /** Days since last message */
  days_since_last_message: number;
  /** Timestamp of calculation */
  calculated_at: string;
}

// ============================================================================
// HEALTH SCORE HISTORY
// ============================================================================

/**
 * Single health score history record
 */
export interface HealthScoreHistory {
  id: string;
  contact_id: string;
  user_id: string;
  score: number;
  components: HealthScoreComponents;
  previous_score: number | null;
  score_delta: number | null;
  trend: HealthScoreTrend;
  alert_generated: boolean;
  alert_type: HealthAlertType | null;
  calculation_method: CalculationMethod;
  messages_analyzed: number;
  calculated_at: string;
  created_at: string;
}

// ============================================================================
// CONTACT WITH HEALTH SCORE
// ============================================================================

/**
 * Contact data with health score information
 */
export interface ContactWithHealthScore {
  id: string;
  user_id: string;
  name: string | null;
  phone_number: string | null;
  profile_picture_url: string | null;
  relationship_type: string | null;
  health_score: number | null;
  health_score_components: HealthScoreComponents | null;
  health_score_trend: HealthScoreTrend | null;
  health_score_updated_at: string | null;
  last_contact_at: string | null;
}

/**
 * Contact at risk (health_score < 40)
 * Matches the v_contacts_at_risk view
 */
export interface ContactAtRisk {
  contact_id: string;
  user_id: string;
  contact_name: string;
  phone_number: string | null;
  profile_picture_url: string | null;
  relationship_type: string | null;
  health_score: number;
  health_score_trend: HealthScoreTrend | null;
  health_score_components: HealthScoreComponents | null;
  health_score_updated_at: string | null;
  frequency_score: number | null;
  recency_score: number | null;
  sentiment_score: number | null;
  reciprocity_score: number | null;
  depth_score: number | null;
  last_interaction_at: string | null;
  risk_level: RiskLevel;
  days_inactive: number;
}

// ============================================================================
// API REQUEST/RESPONSE TYPES
// ============================================================================

/**
 * Request to calculate health score for a single contact
 */
export interface CalculateHealthScoreRequest {
  contactId: string;
}

/**
 * Response from batch health score calculation
 */
export interface BatchCalculateResponse {
  success: boolean;
  mode: 'batch';
  contactsProcessed: number;
  startedAt: string;
  completedAt: string;
  durationMs: number;
  error?: string;
}

/**
 * Response from single contact health score calculation
 */
export interface SingleCalculateResponse {
  success: boolean;
  mode: 'single';
  contactId: string;
  healthScore: number;
  previousScore: number | null;
  scoreDelta: number | null;
  trend: HealthScoreTrend;
  components: HealthScoreComponents;
  messagesAnalyzed: number;
  durationMs: number;
  error?: string;
}

/**
 * Union type for calculate response
 */
export type CalculateHealthScoreResponse = BatchCalculateResponse | SingleCalculateResponse;

// ============================================================================
// HEALTH SCORE STATISTICS
// ============================================================================

/**
 * Summary statistics for user's contact health scores
 */
export interface HealthScoreStats {
  totalContacts: number;
  healthyContacts: number;      // score >= 60
  atRiskContacts: number;       // score 20-39
  criticalContacts: number;     // score < 20
  averageScore: number;
  improvedContacts: number;     // trending up
  decliningContacts: number;    // trending down
  lastCalculatedAt: string | null;
}

/**
 * Distribution of health scores by range
 */
export interface HealthScoreDistribution {
  range: string;
  count: number;
  percentage: number;
}

// ============================================================================
// ALERTS
// ============================================================================

/**
 * Health score alert for user notification
 */
export interface HealthScoreAlert {
  id: string;
  contact_id: string;
  contact_name: string;
  alert_type: HealthAlertType;
  score: number;
  previous_score: number | null;
  score_delta: number | null;
  created_at: string;
  acknowledged: boolean;
  acknowledged_at: string | null;
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Get risk level from health score
 */
export function getRiskLevel(score: number): RiskLevel {
  if (score < 20) return 'critical';
  if (score < 40) return 'high';
  if (score < 60) return 'moderate';
  return 'healthy';
}

/**
 * Get color for risk level
 */
export function getRiskColor(level: RiskLevel): string {
  switch (level) {
    case 'critical': return '#EF4444'; // red-500
    case 'high': return '#F97316';     // orange-500
    case 'moderate': return '#EAB308'; // yellow-500
    case 'healthy': return '#22C55E';  // green-500
  }
}

/**
 * Get color for health score
 */
export function getHealthScoreColor(score: number): string {
  return getRiskColor(getRiskLevel(score));
}

/**
 * Get trend icon name
 */
export function getTrendIcon(trend: HealthScoreTrend): string {
  switch (trend) {
    case 'improving': return 'TrendingUp';
    case 'declining': return 'TrendingDown';
    case 'stable': return 'Minus';
    case 'new': return 'Sparkles';
  }
}

/**
 * Get human-readable alert message
 */
export function getAlertMessage(alertType: HealthAlertType): string {
  switch (alertType) {
    case 'score_critical':
      return 'Relacionamento em estado crítico';
    case 'score_low':
      return 'Relacionamento precisa de atenção';
    case 'rapid_decline':
      return 'Queda rápida na qualidade do relacionamento';
    case 'no_interaction':
      return 'Sem interação há mais de 30 dias';
    case 'sentiment_negative':
      return 'Conversas recentes foram negativas';
  }
}
