/**
 * Copyright (c) 2024 - Present. Aica Engineering. All rights reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
 * Sponsor Deck Generator Types
 * Issue #98 - Gerador de Deck de Patrocinio
 *
 * Tipos TypeScript para geração de apresentacoes PowerPoint (PPTX)
 * para projetos culturais em busca de patrocinadores.
 *
 * @module modules/grants/types/sponsorDeck
 */

// =============================================================================
// REQUEST/RESPONSE TYPES FOR EDGE FUNCTION
// =============================================================================

/**
 * Request payload for the generate-sponsor-deck Edge Function
 */
export interface GenerateDeckRequest {
  /** ID of the approved cultural project */
  projectId: string;
  /** Template ID to use for styling */
  templateId: string;
  /** Additional options for deck generation */
  options: DeckOptions;
}

/**
 * Options for customizing deck generation
 */
export interface DeckOptions {
  /** Tier ID to highlight in the presentation (optional) */
  highlightTierId?: string;
  /** Include financial details in the deck */
  includeFinancials: boolean;
  /** Language for generated content */
  language: 'pt-BR' | 'en-US';
  /** Custom color scheme override (hex color for primary) */
  colorScheme?: string;
}

/**
 * Response from the generate-sponsor-deck Edge Function
 */
export interface GenerateDeckResponse {
  /** Whether generation was successful */
  success: boolean;
  /** Base64-encoded PPTX file content */
  pptxBase64?: string;
  /** Suggested filename for the download */
  filename?: string;
  /** Error message if generation failed */
  error?: string;
  /** Token usage metadata from Gemini */
  usageMetadata?: {
    promptTokenCount: number;
    candidatesTokenCount: number;
    totalTokenCount: number;
  };
}

// =============================================================================
// GEMINI GENERATED CONTENT
// =============================================================================

/**
 * Content generated by Gemini AI for the deck
 */
export interface GeneratedDeckContent {
  /** Project tagline (max 10 words) */
  tagline: string;
  /** Executive summary (max 50 words) */
  executiveSummary: string;
  /** Reasons why companies should sponsor this project */
  whySponsorship: WhySponsorshipItem[];
  /** Call to action phrase for sponsors */
  callToAction: string;
}

/**
 * Individual "Why Sponsor" argument
 */
export interface WhySponsorshipItem {
  /** Short title for the argument */
  title: string;
  /** Detailed description (1-2 sentences) */
  description: string;
}

// =============================================================================
// SLIDE DATA STRUCTURES
// =============================================================================

/**
 * Generic slide data structure
 */
export interface SlideData {
  /** Type of slide determining layout and content */
  type: SlideType;
  /** Slide title */
  title: string;
  /** Slide content (structure varies by type) */
  content: Record<string, unknown>;
}

/**
 * Available slide types in the deck
 */
export type SlideType =
  | 'cover'
  | 'organization'
  | 'project'
  | 'previous-editions'
  | 'impact'
  | 'incentive-law'
  | 'tiers'
  | 'deliverables'
  | 'why-sponsor'
  | 'contact';

/**
 * Cover slide content
 */
export interface CoverSlideContent {
  projectName: string;
  tagline: string;
  organizationName: string;
  logoUrl?: string;
  approvalNumber?: string;
}

/**
 * Organization slide content
 */
export interface OrganizationSlideContent {
  name: string;
  description: string;
  mission?: string;
  achievements: string[];
  logoUrl?: string;
}

/**
 * Project overview slide content
 */
export interface ProjectSlideContent {
  name: string;
  executiveSummary: string;
  objectives: string[];
  duration: string;
  location?: string;
}

/**
 * Previous editions slide content
 */
export interface PreviousEditionsSlideContent {
  editions: Array<{
    year: string;
    highlights: string[];
    metrics?: Record<string, string | number>;
  }>;
}

/**
 * Impact metrics slide content
 */
export interface ImpactSlideContent {
  metrics: Array<{
    label: string;
    value: string | number;
    unit?: string;
    icon?: string;
  }>;
  impactDescription: string;
}

/**
 * Incentive law slide content
 */
export interface IncentiveLawSlideContent {
  lawName: string;
  lawShortName: string;
  jurisdiction: string;
  taxType: string;
  deductionPercentage: number;
  approvalNumber?: string;
  validityPeriod?: string;
  benefits: string[];
}

/**
 * Sponsorship tiers slide content
 */
export interface TiersSlideContent {
  tiers: Array<{
    id: string;
    name: string;
    value: number;
    quantityTotal: number;
    quantityAvailable: number;
    deliverables: string[];
    isHighlighted: boolean;
    color?: string;
  }>;
  currency: string;
}

/**
 * Deliverables breakdown slide content
 */
export interface DeliverablesSlideContent {
  categories: Array<{
    name: string;
    items: Array<{
      title: string;
      description?: string;
      tierNames: string[];
    }>;
  }>;
}

/**
 * Why sponsor slide content
 */
export interface WhySponsorSlideContent {
  arguments: WhySponsorshipItem[];
}

/**
 * Contact slide content
 */
export interface ContactSlideContent {
  organizationName: string;
  contactName: string;
  email: string;
  phone?: string;
  website?: string;
  socialLinks?: Record<string, string>;
  callToAction: string;
}

// =============================================================================
// TEMPLATE CONFIGURATION
// =============================================================================

/**
 * Deck template definition
 */
export interface DeckTemplate {
  /** Unique template ID */
  id: string;
  /** Display name */
  name: string;
  /** Template description */
  description: string;
  /** Color palette */
  colors: TemplateColors;
  /** Font configuration */
  fonts: TemplateFonts;
  /** Preview image URL (optional) */
  previewUrl?: string;
}

/**
 * Template color palette
 */
export interface TemplateColors {
  /** Primary brand color */
  primary: string;
  /** Secondary accent color */
  secondary: string;
  /** Accent color for highlights */
  accent: string;
  /** Background color */
  background: string;
  /** Text color */
  text: string;
}

/**
 * Template font configuration
 */
export interface TemplateFonts {
  /** Font family for headings */
  heading: string;
  /** Font family for body text */
  body: string;
}

// =============================================================================
// BUILT-IN TEMPLATES
// =============================================================================

/**
 * Professional template - Clean, corporate design
 */
export const TEMPLATE_PROFESSIONAL: DeckTemplate = {
  id: 'professional',
  name: 'Profissional',
  description: 'Design limpo e corporativo, ideal para grandes empresas',
  colors: {
    primary: '#1a365d',
    secondary: '#2d4a6f',
    accent: '#ed8936',
    background: '#ffffff',
    text: '#1a202c',
  },
  fonts: {
    heading: 'Arial',
    body: 'Calibri',
  },
};

/**
 * Creative template - Bold, artistic design
 */
export const TEMPLATE_CREATIVE: DeckTemplate = {
  id: 'creative',
  name: 'Criativo',
  description: 'Design ousado e artistico, ideal para projetos culturais',
  colors: {
    primary: '#805ad5',
    secondary: '#d53f8c',
    accent: '#38b2ac',
    background: '#faf5ff',
    text: '#2d3748',
  },
  fonts: {
    heading: 'Arial',
    body: 'Calibri',
  },
};

/**
 * Institutional template - Formal, government-style design
 */
export const TEMPLATE_INSTITUTIONAL: DeckTemplate = {
  id: 'institutional',
  name: 'Institucional',
  description: 'Design formal, ideal para projetos governamentais',
  colors: {
    primary: '#2c5282',
    secondary: '#276749',
    accent: '#d69e2e',
    background: '#f7fafc',
    text: '#1a202c',
  },
  fonts: {
    heading: 'Arial',
    body: 'Calibri',
  },
};

/**
 * All available templates
 */
export const DECK_TEMPLATES: DeckTemplate[] = [
  TEMPLATE_PROFESSIONAL,
  TEMPLATE_CREATIVE,
  TEMPLATE_INSTITUTIONAL,
];

/**
 * Get template by ID
 */
export function getTemplateById(id: string): DeckTemplate | undefined {
  return DECK_TEMPLATES.find(t => t.id === id);
}

// =============================================================================
// UI STATE TYPES
// =============================================================================

/**
 * Wizard step definition
 */
export type DeckWizardStep =
  | 'template'
  | 'options'
  | 'preview'
  | 'generating'
  | 'done';

/**
 * Wizard step configuration
 */
export interface DeckWizardStepConfig {
  id: DeckWizardStep;
  title: string;
  description: string;
}

/**
 * Wizard steps in order
 */
export const DECK_WIZARD_STEPS: DeckWizardStepConfig[] = [
  {
    id: 'template',
    title: 'Escolher Template',
    description: 'Selecione o estilo visual da apresentação',
  },
  {
    id: 'options',
    title: 'Personalizar',
    description: 'Configure as opções do deck',
  },
  {
    id: 'preview',
    title: 'Visualizar',
    description: 'Confira a estrutura da apresentação',
  },
  {
    id: 'generating',
    title: 'Gerando',
    description: 'Criando sua apresentação...',
  },
  {
    id: 'done',
    title: 'Pronto',
    description: 'Seu deck esta pronto para download',
  },
];

/**
 * Slide preview data for wizard preview step
 */
export interface SlidePreview {
  number: number;
  type: SlideType;
  title: string;
  description: string;
}

/**
 * Default slide structure for preview
 */
export const DEFAULT_SLIDE_STRUCTURE: SlidePreview[] = [
  { number: 1, type: 'cover', title: 'Capa', description: 'Nome do projeto e tagline' },
  { number: 2, type: 'organization', title: 'Proponente', description: 'Sobre a organizacao' },
  { number: 3, type: 'project', title: 'O Projeto', description: 'Resumo executivo e objetivos' },
  { number: 4, type: 'previous-editions', title: 'Edições Anteriores', description: 'Histórico e resultados' },
  { number: 5, type: 'impact', title: 'Impacto', description: 'Métricas e alcance' },
  { number: 6, type: 'incentive-law', title: 'Lei de Incentivo', description: 'Beneficios fiscais' },
  { number: 7, type: 'tiers', title: 'Cotas', description: 'Niveis de patrocinio' },
  { number: 8, type: 'deliverables', title: 'Contrapartidas', description: 'O que o patrocinador recebe' },
  { number: 9, type: 'why-sponsor', title: 'Por que Patrocinar', description: 'Argumentos de venda' },
  { number: 10, type: 'contact', title: 'Contato', description: 'Como entrar em contato' },
];
