/**
 * QuickCapture Component
 * Minimalist moment capture with real-time AI analysis
 *
 * Philosophy: "Peca o minimo, entregue o maximo"
 * - 1 field (auto-focused)
 * - Inline audio recorder with auto-transcription
 * - Real-time AI suggestions
 * - Tags auto-generated by AI in background
 */

import React, { useState, useEffect, useRef, useCallback } from 'react';
import { createNamespacedLogger } from '@/lib/logger';
import { motion, AnimatePresence } from 'framer-motion';

const log = createNamespacedLogger('QuickCapture');
import {
  SparklesIcon,
  LightBulbIcon,
} from '@heroicons/react/24/solid';
import { CreateMomentInput } from '../../types/moment';
import { analyzeContentRealtime } from '../../services/aiAnalysisService';
import { AudioRecorder } from './AudioRecorder';
import { transcribeAudio } from '../../services/momentPersistenceService';

interface QuickCaptureProps {
  onSubmit: (moment: CreateMomentInput) => Promise<void>;
  onCancel?: () => void;
  /** Initial content to pre-populate */
  initialContent?: string;
  /** Compact mode for sidebar display */
  compact?: boolean;
}

interface AISuggestion {
  type: 'reflection' | 'question' | 'pattern';
  message: string;
  icon?: string;
}

export function QuickCapture({
  onSubmit,
  onCancel,
  initialContent = '',
  compact = false,
}: QuickCaptureProps) {
  const [content, setContent] = useState(initialContent);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isTranscribing, setIsTranscribing] = useState(false);
  const [wasAudioRecorded, setWasAudioRecorded] = useState(false);
  const [aiSuggestion, setAiSuggestion] = useState<AISuggestion | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const analysisTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  // Update content when initialContent changes
  useEffect(() => {
    if (initialContent && initialContent !== content) {
      setContent(initialContent);
    }
  }, [initialContent]);

  // Auto-focus on mount
  useEffect(() => {
    textareaRef.current?.focus();
  }, []);

  // Real-time AI analysis (debounced 3s)
  useEffect(() => {
    if (content.trim().length < 20) {
      setAiSuggestion(null);
      return;
    }

    // Clear previous timeout
    if (analysisTimeoutRef.current) {
      clearTimeout(analysisTimeoutRef.current);
    }

    // Set new timeout
    analysisTimeoutRef.current = setTimeout(async () => {
      setIsAnalyzing(true);
      try {
        const suggestion = await analyzeContentRealtime(content);
        setAiSuggestion(suggestion);
      } catch (error) {
        log.error('Error analyzing content:', error);
      } finally {
        setIsAnalyzing(false);
      }
    }, 3000);

    return () => {
      if (analysisTimeoutRef.current) {
        clearTimeout(analysisTimeoutRef.current);
      }
    };
  }, [content]);

  // Auto-transcribe audio recording into textarea
  const handleRecordingComplete = useCallback(async (blob: Blob) => {
    try {
      setIsTranscribing(true);
      log.debug('Transcribing audio for QuickCapture', { size: blob.size });
      const text = await transcribeAudio(blob);
      if (text) {
        setContent(prev => prev ? `${prev}\n\n${text}` : text);
        setWasAudioRecorded(true);
      }
    } catch (err) {
      log.error('Audio transcription failed:', err);
      alert('Erro na transcrição do áudio. Tente novamente ou digite o texto.');
    } finally {
      setIsTranscribing(false);
    }
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!content.trim()) {
      textareaRef.current?.focus();
      return;
    }

    try {
      setIsSubmitting(true);

      await onSubmit({
        type: wasAudioRecorded ? 'audio' : 'text',
        content: content.trim(),
      });

      // Reset form
      setContent('');
      setWasAudioRecorded(false);
      setAiSuggestion(null);
    } catch (error) {
      log.error('Error submitting moment:', error);
      alert('Erro ao salvar momento. Tente novamente.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    // Cmd/Ctrl + Enter to submit
    if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
      handleSubmit(e as any);
    }
  };

  return (
    <motion.form
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      onSubmit={handleSubmit}
      className={`ceramic-card ${compact ? 'p-4 space-y-3' : 'p-6 space-y-4'}`}
    >
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className={`ceramic-concave ${compact ? 'p-1.5' : 'p-2'} rounded-lg`}>
            <SparklesIcon className={`${compact ? 'h-4 w-4' : 'h-5 w-5'} text-purple-500`} />
          </div>
          <h3 className={`${compact ? 'text-sm' : 'text-lg'} font-bold text-ceramic-text-primary`}>
            {compact ? 'Novo Momento' : 'O que esta te movendo agora?'}
          </h3>
        </div>
        {(isAnalyzing || isTranscribing) && (
          <div className="flex items-center gap-2 text-xs text-ceramic-text-tertiary">
            <div className="w-2 h-2 bg-purple-500 rounded-full animate-pulse" />
            {isTranscribing ? 'Transcrevendo...' : 'Analisando...'}
          </div>
        )}
      </div>

      {/* Main Text Area */}
      <div>
        <textarea
          ref={textareaRef}
          value={content}
          onChange={(e) => setContent(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder={isTranscribing ? 'Transcrevendo audio...' : (compact ? 'O que esta te movendo agora?' : 'Comece a escrever... A IA vai te ajudar a refletir.')}
          rows={compact ? 3 : 6}
          disabled={isTranscribing}
          className="w-full px-4 py-3 border-2 border-ceramic-text-secondary/20 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent focus:outline-none resize-none transition-all text-base disabled:opacity-60 disabled:bg-ceramic-50"
        />
        {/* Character count + AudioRecorder inline */}
        <div className="flex items-center justify-between mt-2">
          <p className="text-xs text-ceramic-text-tertiary">
            {content.length} caracteres
          </p>
          <div className="flex items-center gap-2">
            <AudioRecorder
              onRecordingComplete={handleRecordingComplete}
              disabled={isSubmitting || isTranscribing}
            />
            <span className="text-xs text-ceramic-text-tertiary">
              Ctrl+Enter salvar
            </span>
          </div>
        </div>
      </div>

      {/* AI Suggestion (appears after 3s of no typing) */}
      <AnimatePresence>
        {aiSuggestion && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.3 }}
            className={`ceramic-tray rounded-lg ${compact ? 'p-3' : 'p-4'} border-2 border-purple-500/20 bg-purple-500/5`}
          >
            <div className="flex items-start gap-2">
              <LightBulbIcon className={`${compact ? 'w-4 h-4' : 'w-5 h-5'} text-purple-500 flex-shrink-0 mt-0.5`} />
              <div className="flex-1">
                <p className={`${compact ? 'text-[10px]' : 'text-xs'} font-bold text-purple-700 dark:text-purple-400 mb-1`}>
                  {aiSuggestion.type === 'reflection' && 'Reflexao sugerida'}
                  {aiSuggestion.type === 'question' && 'Pergunta para aprofundar'}
                  {aiSuggestion.type === 'pattern' && 'Padrao identificado'}
                </p>
                <p className="text-sm text-ceramic-text-secondary">
                  {aiSuggestion.message}
                </p>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Action Buttons */}
      <div className="flex items-center justify-between pt-2 border-t border-ceramic-text-secondary/10">
        <p className="text-xs text-ceramic-text-tertiary">
          Tags e humor gerados automaticamente pela IA
        </p>

        <div className="flex items-center gap-2">
          {onCancel && (
            <button
              type="button"
              onClick={onCancel}
              className="ceramic-concave px-4 py-2 text-sm font-medium text-ceramic-text-primary hover:scale-95 active:scale-90 transition-all"
            >
              Cancelar
            </button>
          )}
          <button
            type="submit"
            disabled={isSubmitting || isTranscribing || !content.trim()}
            className={`ceramic-convex ${compact ? 'px-4 py-1.5 text-xs' : 'px-6 py-2 text-sm'} font-bold bg-gradient-to-r from-purple-500 to-blue-600 text-white hover:scale-[1.02] active:scale-95 disabled:opacity-50 disabled:hover:scale-100 transition-all flex items-center gap-2`}
          >
            {isSubmitting ? (
              <>
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                Salvando...
              </>
            ) : (
              <>
                <SparklesIcon className="w-4 h-4" />
                Salvar (+5 CP)
              </>
            )}
          </button>
        </div>
      </div>

      {/* Info Footer */}
      {!compact && (
        <div className="flex items-center gap-2 p-3 bg-purple-50 dark:bg-purple-900/10 rounded-lg">
          <SparklesIcon className="h-4 w-4 text-purple-500 flex-shrink-0" />
          <p className="text-xs text-purple-900 dark:text-purple-300">
            Seu momento sera indexado com IA para descobrir padroes e insights.
          </p>
        </div>
      )}
    </motion.form>
  );
}
