/**
 * QuickCapture Component
 * Minimalist moment capture with real-time AI analysis
 *
 * Philosophy: "Peca o mínimo, entregue o máximo"
 * - MultiModalInput (text + áudio + photo)
 * - Real-time AI suggestions
 * - Tags auto-generated by AI in background
 * - Fire-and-forget intent extraction for cross-module routing
 */

import { useState, useEffect, useRef, useCallback } from 'react';
import { createNamespacedLogger } from '@/lib/logger';
import { motion, AnimatePresence } from 'framer-motion';

const log = createNamespacedLogger('QuickCapture');
import {
  SparklesIcon,
  LightBulbIcon,
} from '@heroicons/react/24/solid';
import { CreateMomentInput } from '../../types/moment';
import { analyzeContentRealtime } from '../../services/aiAnalysisService';
import { MultiModalInput, type MultiModalOutput } from '@/components/features/MultiModalInput';
import { describeImage } from '../../services/momentPersistenceService';
import { extractIntent } from '@/services/universalInputService';

interface QuickCaptureProps {
  onSubmit: (moment: CreateMomentInput) => Promise<void>;
  onCancel?: () => void;
  /** Initial content to pre-populate */
  initialContent?: string;
  /** Compact mode for sidebar display */
  compact?: boolean;
}

interface AISuggestion {
  type: 'reflection' | 'question' | 'pattern';
  message: string;
  icon?: string;
}

export function QuickCapture({
  onSubmit,
  onCancel,
  compact = false,
}: QuickCaptureProps) {
  const [aiSuggestion, setAiSuggestion] = useState<AISuggestion | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const lastAnalyzedRef = useRef('');
  const analysisTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Cleanup analysis timeout on unmount
  useEffect(() => {
    return () => {
      if (analysisTimeoutRef.current) {
        clearTimeout(analysisTimeoutRef.current);
      }
    };
  }, []);

  // Debounced real-time AI analysis, wired via MultiModalInput's onTextChange
  const handleTextChange = useCallback((text: string) => {
    if (text.trim().length < 20) {
      setAiSuggestion(null);
      return;
    }

    if (text === lastAnalyzedRef.current) return;

    if (analysisTimeoutRef.current) {
      clearTimeout(analysisTimeoutRef.current);
    }

    analysisTimeoutRef.current = setTimeout(async () => {
      setIsAnalyzing(true);
      try {
        const suggestion = await analyzeContentRealtime(text);
        setAiSuggestion(suggestion);
        lastAnalyzedRef.current = text;
      } catch (error) {
        log.error('Error analyzing content:', error);
      } finally {
        setIsAnalyzing(false);
      }
    }, 3000);
  }, []);

  // Handle MultiModalInput submission → map to CreateMomentInput
  const handleMultiModalSubmit = useCallback(async (input: MultiModalOutput) => {
    let content = input.text;

    // For photo moments without text, generate AI description
    if (input.type === 'photo' && !content.trim() && input.metadata?.photoFile) {
      try {
        content = await describeImage(input.metadata.photoFile);
      } catch (err) {
        log.warn('Image description failed, using fallback:', err);
        content = '[Momento com foto]';
      }
    }

    const momentInput: CreateMomentInput = {
      type: input.type,
      content,
      audioBlob: input.metadata?.audioBlob,
      photoFile: input.metadata?.photoFile,
    };

    await onSubmit(momentInput);

    // Fire-and-forget intent extraction for cross-module routing
    if (content.trim()) {
      const contentTypeMap = { audio: 'audio_transcription', photo: 'ocr', text: 'text' } as const;
      extractIntent({
        rawText: content,
        source: 'journey',
        content_type: contentTypeMap[input.type],
        moduleContext: 'journey',
      }).catch(err => {
        log.warn('Intent extraction failed (non-blocking):', err);
      });
    }

    // Reset AI suggestion
    setAiSuggestion(null);
    lastAnalyzedRef.current = '';
  }, [onSubmit]);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className={`ceramic-card ${compact ? 'p-4 space-y-3' : 'p-6 space-y-4'}`}
      data-tour="quick-capture"
    >
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className={`ceramic-concave ${compact ? 'p-1.5' : 'p-2'} rounded-lg`}>
            <SparklesIcon className={`${compact ? 'h-4 w-4' : 'h-5 w-5'} text-ceramic-accent`} />
          </div>
          <h3 className={`${compact ? 'text-sm' : 'text-lg'} font-bold text-ceramic-text-primary`}>
            {compact ? 'Novo Momento' : 'O que esta te movendo agora?'}
          </h3>
        </div>
        {isAnalyzing && (
          <div className="flex items-center gap-2 text-xs text-ceramic-text-tertiary">
            <div className="w-2 h-2 bg-ceramic-accent rounded-full animate-pulse" />
            Analisando...
          </div>
        )}
      </div>

      {/* MultiModal Input */}
      <MultiModalInput
        onSubmit={handleMultiModalSubmit}
        onTextChange={handleTextChange}
        placeholder={compact ? 'O que esta te movendo agora?' : 'Comece a escrever... A IA vai te ajudar a refletir.'}
        compact={compact}
        minRows={compact ? 1 : 5}
        submitLabel="Salvar"
        onCancel={onCancel}
        showAudio
        showPhoto
      />

      {/* AI Suggestion (appears after 3s of no typing) — question type removed (#703) */}
      <AnimatePresence>
        {aiSuggestion && aiSuggestion.type !== 'question' && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.3 }}
            className={`ceramic-tray rounded-lg ${compact ? 'p-3' : 'p-4'} border-2 border-ceramic-accent/20 bg-ceramic-accent/5`}
          >
            <div className="flex items-start gap-2">
              <LightBulbIcon className={`${compact ? 'w-4 h-4' : 'w-5 h-5'} text-ceramic-accent flex-shrink-0 mt-0.5`} />
              <div className="flex-1">
                <p className="text-xs font-bold text-ceramic-accent mb-1">
                  {aiSuggestion.type === 'reflection' && 'Reflexão sugerida'}
                  {aiSuggestion.type === 'pattern' && 'Padrão identificado'}
                </p>
                <p className="text-sm text-ceramic-text-secondary">
                  {aiSuggestion.message}
                </p>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Info Footer */}
      {!compact && (
        <div className="flex items-center gap-2 p-3 bg-ceramic-accent/10 rounded-lg">
          <SparklesIcon className="h-4 w-4 text-ceramic-accent flex-shrink-0" />
          <p className="text-xs text-ceramic-accent">
            Seu momento sera indexado com IA para descobrir padrões e insights.
          </p>
        </div>
      )}
    </motion.div>
  );
}
