-- ============================================================================
-- Autonomous Agents: Notification System
-- Sprint: Agentes Autônomos
-- Stores notifications generated by proactive agents for user consumption
-- ============================================================================

-- ============================================================================
-- TABLE: agent_notifications
-- Notifications from autonomous agents (morning_briefing, deadline_watcher,
-- pattern_analyzer, life_council) displayed via notification bell in header
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Agent identification
  agent_name TEXT NOT NULL,  -- 'morning_briefing', 'deadline_watcher', 'pattern_analyzer', 'life_council'
  notification_type TEXT NOT NULL
    CHECK (notification_type IN ('insight', 'deadline', 'pattern', 'action', 'system')),

  -- Content
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  metadata JSONB DEFAULT '{}',

  -- Read tracking
  read_at TIMESTAMPTZ,  -- NULL when unread

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_agent_notif_user_created
  ON agent_notifications(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_notif_unread
  ON agent_notifications(user_id)
  WHERE read_at IS NULL;

-- ============================================================================
-- RLS POLICIES
-- ============================================================================

ALTER TABLE agent_notifications ENABLE ROW LEVEL SECURITY;

-- Users can read their own notifications
DROP POLICY IF EXISTS "Users view own agent notifications" ON agent_notifications;
CREATE POLICY "Users view own agent notifications" ON agent_notifications
  FOR SELECT USING (auth.uid() = user_id);

-- Users can update their own notifications (mark as read)
DROP POLICY IF EXISTS "Users update own agent notifications" ON agent_notifications;
CREATE POLICY "Users update own agent notifications" ON agent_notifications
  FOR UPDATE USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- DELETE intentionally omitted — notifications are agent-generated,
-- cleanup handled by service role. Users can only read and mark-as-read.

-- Service role full access (insert, cleanup, admin operations)
DROP POLICY IF EXISTS "Service role full access agent notifications" ON agent_notifications;
CREATE POLICY "Service role full access agent notifications" ON agent_notifications
  FOR ALL TO service_role USING (true)
  WITH CHECK (true);

-- ============================================================================
-- GRANTS
-- ============================================================================

GRANT SELECT, UPDATE ON agent_notifications TO authenticated;
GRANT ALL ON agent_notifications TO service_role;

-- ============================================================================
-- RPC: get_unread_notification_count
-- Returns count of unread notifications for a user
-- ============================================================================

CREATE OR REPLACE FUNCTION get_unread_notification_count(p_user_id UUID)
RETURNS INTEGER
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COUNT(*)::INTEGER FROM agent_notifications
  WHERE user_id = p_user_id AND read_at IS NULL;
$$;

-- ============================================================================
-- RPC: mark_notifications_read
-- Marks specific notifications as read for a user
-- ============================================================================

CREATE OR REPLACE FUNCTION mark_notifications_read(p_user_id UUID, p_notification_ids UUID[])
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE agent_notifications
  SET read_at = NOW()
  WHERE user_id = p_user_id
    AND id = ANY(p_notification_ids)
    AND read_at IS NULL;
END;
$$;

-- ============================================================================
-- GRANTS for RPCs
-- ============================================================================

GRANT EXECUTE ON FUNCTION get_unread_notification_count TO authenticated;
GRANT EXECUTE ON FUNCTION mark_notifications_read TO authenticated;
